apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: emkx9uzbr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/emkx9uzbr-java-quarkus-gitops